### ISSUE TITLE
Enable hyperlink on parameter for verification

### ISSUE THREAD

**Issue by cryptopoly** [Mleipper/AirDropProjectboard#12]
URL makes easier to review
-end goal would be to pull the tweet info through

<img width="1380" alt="Screenshot 2019-11-14 at 12 42 04" src="https://user-images.githubusercontent.com/31970407/68858127-3df10980-06dc-11ea-9cf7-36ee15a5a8fc.png">

**Comment by Mleipper** [comment]
Can we clarify what you mean by Pull tweet through, does this mean it should get the text of the tweet and display it in place of the URI

**Comment by cryptopoly** [comment]
essentially just make the url that's pulled through from actionparam to be a clickable hyperlink, so easier to plough through validation

**Comment by Mleipper** [comment]
![image](https://user-images.githubusercontent.com/9982768/68974499-ca88ee00-07e8-11ea-9004-79c1a32ed040.png)
one clickable link below the printed link
