### ISSUE TITLE
Temporarily change column title on web front end - from 'awaiting payout' do 'Payout Due 30th Nov'

### ISSUE THREAD

**Issue by cryptopoly** [Mleipper/AirDropProjectboard#13]
<img width="1509" alt="Screenshot 2019-11-14 at 14 49 09" src="https://user-images.githubusercontent.com/31970407/68867623-10ad5700-06ee-11ea-8adb-a45b46018830.png">

**Comment by Mleipper** [comment]
![image](https://user-images.githubusercontent.com/9982768/68898925-64d52d00-0728-11ea-892b-e7cacab1370c.png)
change as requested
