### ISSUE TITLE
XLR Wallet Address Error

### ISSUE THREAD

**Issue by cryptopoly** [Mleipper/AirDropProjectboard#4]
Users not able to save their XLR address!

Example address - SgJziTfhmQw1TJB8tqGsRuKVyauTnPqSZH

<img width="418" alt="Screenshot 2019-10-18 at 10 55 52" src="https://user-images.githubusercontent.com/31970407/67087435-d4441500-f19a-11e9-8bdd-a6364a1a9b26.png">

**Comment by cryptopoly** [comment]
@Mleipper this is high prio if possible :D

**Comment by Mleipper** [comment]
This issue was sorted a while ago, just forgot to close.
