### ISSUE TITLE
Rewards that have been filled (e.g. 500/500), users can still do task and are unhappy not getting paid

### ISSUE THREAD

**Issue by cryptopoly** [Mleipper/AirDropProjectboard#7]
If a reward has run out it’s still visible at the moment and people don’t know they haven’t got the reward until after they’ve clicked, so they’re cheesed that the completed the task but get nothing for it.

**Comment by Mleipper** [comment]
Just seen this while knocking off some of the easy tickets, I'll look at this in the morning when I'm a little more alert.

**Comment by Mleipper** [comment]
![image](https://user-images.githubusercontent.com/9982768/68721680-13ebfa00-05ab-11ea-91b4-40a53415b746.png)
not sure if @pleipper has edited the backend on this already, however, the above is the error I got from the system in its current state.
