### ISSUE TITLE
Quick fix - show numbers fully e.g. 500/500

### ISSUE THREAD

**Issue by cryptopoly** [Mleipper/AirDropProjectboard#8]
Reduce text size ultra quick maybe?

<img width="511" alt="Screenshot 2019-11-07 at 12 31 41" src="https://user-images.githubusercontent.com/31970407/68389317-8ea3b800-015a-11ea-9c2e-811a55a1d6a8.png">

**Comment by Mleipper** [comment]
![image](https://user-images.githubusercontent.com/9982768/68721349-f9655100-05a9-11ea-81f0-86a8deccac65.png)
Edited CSS to lower font size from 70 to 20 px
